# Generated by Django 3.2.7 on 2021-12-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
